### ISSUE TITLE
Using DHCP leads to multiple default routes, broken DNS resolution

### ISSUE THREAD

**Issue by stoopsj** [jpetazzo/pipework#47]
When I set up a pipework interface to give my container an external DHCP IP on the same network as my host system, I end up with two default routes in the container. One is the docker-supplied default route over eth0. The other is the DHCP supplied default route over eth1. This breaks DNS for some reason (wireshark shows the requests go out and come back to the host, but never get into the container...) 

Deleting the default route over eth0 allows DNS to work again. fixes the issue:
```bash
ip netns exec $NSPID route del 0.0.0.0 eth0
```

Perhaps pipework could check for a new default route on the pipework-managed interface, and delete the default route via eth0 if it finds a new one?

**Comment by jpetazzo** [comment]
This should be solved by the new DHCP strategy (where the DHCP client runs in a separate container :-))

**Comment by dreamcat4** [comment]
@stoopsj Can you please post the details of your custom `udhcpc` script solution here? I would really appreciate that...

Since still encountering various other issues with the other `dhcp` clients / methods, which includes Jerome's new busybox containers solution too.

Got this same error as you reported here ^^ myself today. That was with ubuntu trusty's `udhcpc`. As things currently stand your solution seems like it may be an easier solution. Just need to get up and running again for the time being. Many thanks.

**Comment by dreamcat4** [comment]
OK. Hi again.

Right well it turned out that the version of the udhcpc script that comes with the official `trusty` - `14.04` apt pkg of `udhcpc` was no good. Too old. So rather than hack together my own modified script it seemed a better idea just to upgrade my container to the latest `15.10` ubuntu `wily`... which has newer version of said pkg, and the script looks so different it's hardly recognizable.

Many thanks @stoopsj for the clues you've given here.

This was the bit where I could see the old version of the script was clearly screwing things up:

```sh
+ [ 0a:00:00:02:00:03 ]
+ ip netns exec 7378 ip link set dev eth0 address 0a:00:00:02:00:03
+ ip netns exec 7378 udhcpc -qi eth0 -x hostname:tvh
udhcpc (v1.21.1) started
Sending discover...
Sending select for 192.168.2.3...
Lease of 192.168.2.3 obtained, lease time 268435455
/etc/udhcpc/default.script: Resetting default routes
SIOCDELRT: No such process
/etc/udhcpc/default.script: Adding DNS 192.168.1.1

```

So it already had the lease by that time. I reference this solution in my other issue (with the new busybox containers).

**Comment by stoopsj** [comment]
Sorry, @dreamcat4, but I am no longer at the company where I wrote this script, so I don't have access to it anymore. Good luck!

**Comment by dreamcat4** [comment]
No problems. OK now.

**Comment by jpetazzo** [comment]
Sorry, I lag horribly. Let me know if this should be re-opened.
